public enum MenuType
{
    None,
    Main,
    Play,
    Singleplayer,
    Garage,
    Multiplayer,
    Options,
    OfflineTournament,
    SingleplayerMaps,
    Modification,
    MultiplayerRace,
    JoinMultiplayerRace,
    HostMultiplayerRace,
    MultiplayerCompleteMenu,
    VolumeMenu,
    AchievementMenu
}